#!/usr/bin/env python3
"""
Check evidence chain immutability.

Prevents direct modification of evidence chain files.
"""

import sys


def main():
    """Check if evidence chain files are being modified."""
    if len(sys.argv) < 2:
        sys.exit(0)

    evidence_files = [f for f in sys.argv[1:] if "evidence_chain" in f.lower()]

    if evidence_files:
        print("=" * 60)
        print("EVIDENCE CHAIN MODIFICATION BLOCKED")
        print("=" * 60)
        print()
        print("The following evidence chain files cannot be modified directly:")
        for f in evidence_files:
            print(f"  - {f}")
        print()
        print("Evidence chains are cryptographic proofs of evaluation integrity.")
        print("They must be generated by the evaluation system, not edited manually.")
        print()
        print("If you need to regenerate an evidence chain:")
        print("  python -m scribegoat.generate_evidence_chain --run_id <ID>")
        print("=" * 60)
        sys.exit(1)

    sys.exit(0)


if __name__ == "__main__":
    main()
